version: '3'
services:
  node-server:
    build: project/server
    ports: 
      - "3500:3000"
    depends_on:
      - mongo
    volumes:
      - "./project/server/upload:/polyphonic/upload"

  mongo:
    build: database/
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - "27018:27017"
    expose:
      - "27017"
    volumes:
      - "/var/lib/mongo:/data/db"

  grafana:
    build: grafana/
    ports: 
      - "4000:3000"
    # volumes:
    #   - "./project/server/upload:/polyphonic/upload"
