version: '3'
services:
  node-server:
    build: project/server
    ports: 
      - "3500:3500"
    depends_on:
      - mongo

  mongo:
    build: database/
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    ports:
      - "27017:27017"
    expose:
      - "27017"
    # volumes:
    #   - 